### PR TITLE
resolves #15 - add badges for visiblity

### LINKED ISSUE #15: Add badges for travis and npm
- add badges to indicate the status and version

### PR DESCRIPTION
**Pull request by JoeChapman**
npm and travis ci badges for fun

### CODE REVIEW

**Comment by joefitter** [comment]
👍

**Comment by JoeChapman** [comment]
@easternbloc @danielepolencic

**Comment by easternbloc** [comment]
@JoeChapman stop spamming me. I'll merge when the tests pass.

**Pull request merged**
