### PR TITLE
Use hof-template-partials for common views

### PR DESCRIPTION
**Pull request by JoeChapman**
resolves https://github.com/UKHomeOffice/hof-bootstrap/issues/16

- install hof-template-partials
- update express-partial-templates

hof-template-partials exports views and translations
This update means we can remove the commonly used views from the service that consumes bootstrap and import the views from hof-template-partials

### CODE REVIEW

**Comment by joefitter** [comment]
this LGTM but we should also point to the template-partials for terms/cookies

**Comment by joefitter** [comment]
will submit a PR with these changes on GRO in a sec

**Comment by JoeChapman** [comment]
ok, I'll add that in another pr after this

**Comment by JoeChapman** [comment]
@easternbloc @danielepolencic please take a look at this

**Pull request merged**
